### ISSUE TITLE
[Task] Refactor JMC related code when upstream refactoring is complete

### ISSUE THREAD

**Issue by Josh-Matsuoka** [cryostatio/cryostat-core#173]
Currently we're embedding classes from the flightrecorder, rjmx, jdp, and ui/common. There's an ongoing effort to refactor flightrecorder.configuration and ui.common into jmc-core. Once this upstream refactoring is done and the changes are available on maven central we should update cryostat accordingly.

Depends on the following upstream issues:
https://bugs.openjdk.org/browse/JMC-7308
https://bugs.openjdk.org/browse/JMC-7307

Related: https://github.com/cryostatio/cryostat-core/issues/95 https://github.com/cryostatio/cryostat-core/issues/22

**Comment by aptmac** [comment]
Just noticed that there were a couple of issues still open related to the dependency on jmc/application.

This was addressed in commit https://github.com/cryostatio/cryostat-core/commit/34c5e0e423069c748553a4a51c4c3f5c9fda5e54.
