### ISSUE TITLE
[Task] Use org.openjdk.jmc.jdp from maven central

### ISSUE THREAD

**Issue by aptmac** [cryostatio/cryostat-core#225]
The jdp bundle was moved from JMC application to core back in 2020 [[0]](
https://github.com/openjdk/jmc/commit/87905922639233c74e9b3d6806b3854e71e160f0), and was a part of the 8.0.0 release.

Since cryostat-core was updated to use JMC 8.2.0 sources as of https://github.com/cryostatio/cryostat-core/pull/201, perhaps it'd be nice to also bring in jdp from maven central alongside it's other core counterparts (common/flightrecorder/etc.).

[0] https://github.com/openjdk/jmc/commit/87905922639233c74e9b3d6806b3854e71e160f0

**Comment by andrewazores** [comment]
Related to https://github.com/cryostatio/cryostat-core/issues/223

**Comment by andrewazores** [comment]
Closed by #225
