### ISSUE TITLE
[Task] Replace JSoup with Jackson

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-core#300]
JSoup is used for some light processing of `.jfc` XML documents. Unfortunately, we also expose the JSoup `Document` class as part of our own public API.

1. The `Document` type should be abstracted away so that any library used for processing XML is an internal implementation detail of this library
2. JSoup should be replaced by Jackson, since Jackson handles both XML and JSON and is already used in other parts of the Cryostat project as well.

**Comment by Josh-Matsuoka** [comment]
Digging into this a bit further and experimenting with it, it looks like there are 2 potential issues we're going to run into with this

The first is that attributes are lost when deserializing then reserializing, the attributes are turned into normal tags which would break the jfc schema. [1]

The second issue is that it doesn't support cases where there is an attribute and later a tag with the same name. This occurs in the JFC templates where the setting tag has an attribute 'control' and there is a separate 'control' tag later on. [2]

[1] https://github.com/FasterXML/jackson-dataformat-xml/issues/613
[2] https://github.com/FasterXML/jackson-dataformat-xml/issues/555

We should still abstract away the Document type, but I think it's better to keep using jsoup for the moment.

**Comment by andrewazores** [comment]
Good findings, thanks. It's unfortunate but I think your conclusion that we need to keep the dependency is correct, or else we can't do any validations on `.jfc`s.
