### ISSUE TITLE
Published Builds

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-core#92]
Builds should be published somewhere public like Maven Central so that dependent projects (ex. Cryostat itself) can easily consume this -core library without having to first manually retrieve and build it.

**Comment by andrewazores** [comment]
@ebaron @jiekang any thoughts about where this should go?

**Comment by jiekang** [comment]
If cryostat-core is a Java library, I think publishing it to Maven Central makes sense.

**Comment by ebaron** [comment]
Maven Central makes sense. I'm not sure how useful it will be to other consumers, but I suppose it doesn't have to be.

**Comment by andrewazores** [comment]
I think we can just publish to GitHub Packages. We can add that as a repository to the main Cryostat `pom.xml` under a `ci` profile or something so that it's only searched if building with `-Pci`, since pulling from GH Packages requires authentication. We can set up CI within this repo to publish to Packages with each PR/merge, and then set up Cryostat to pull from Packages rather than rebuilding -core every time, too.

**Comment by andrewazores** [comment]
@ebaron any opinions on ^ ?

**Comment by ebaron** [comment]
That makes sense to me. I say we give it a try.

**Comment by andrewazores** [comment]
If the above linked issues work out well then I think we can consider this as resolved. Perhaps we do want to publish snapshots on every merge to `main` before closing this.

**Comment by andrewazores** [comment]
I think we can consider this done, now. Snapshot builds from every push to `main` may be worth exploring separately, but don't seem immediately valuable for us at the moment.

**Comment by ebaron** [comment]
Example workflow using JReleaser: https://github.com/RedHatInsights/insights-java-agent/blob/dff25aac0e3174a7a679b394e74ab893a70a2767/.github/workflows/release.yaml

**Comment by andrewazores** [comment]
Looks good (finally): https://repo.maven.apache.org/maven2/io/cryostat/cryostat-core/
